In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.rand(2,4,5)
print(data)
p = pd.Panel(data)
print(p)

[[[0.33639029 0.42808179 0.19255401 0.02552294 0.08938459]
  [0.34338012 0.2962858  0.15029501 0.10408847 0.27497513]
  [0.69761966 0.10723851 0.42522366 0.37046817 0.58749552]
  [0.2630116  0.39019931 0.64927859 0.91031923 0.46288776]]

 [[0.91219615 0.12863083 0.59932111 0.0638757  0.8395321 ]
  [0.86830793 0.7776833  0.68991378 0.76790344 0.62318044]
  [0.70416581 0.89566526 0.47442041 0.11154277 0.02461457]
  [0.71809773 0.69426814 0.52826819 0.20725565 0.79005925]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 5 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 4


In [3]:
data = {
    'Item1': pd.DataFrame(np.random.rand(4,3)),
    'Item2': pd.DataFrame(np.random.rand(4,2))
}
p = pd.Panel(data)
print(p)

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2


In [4]:
p = pd.Panel()
print(p)

<class 'pandas.core.panel.Panel'>
Dimensions: 0 (items) x 0 (major_axis) x 0 (minor_axis)
Items axis: None
Major_axis axis: None
Minor_axis axis: None


In [5]:
data = {
    'Item1': pd.DataFrame(np.random.rand(4,3)),
    'Item2': pd.DataFrame(np.random.rand(4,2))
}
p = pd.Panel(data)
print(p['Item1'])

          0         1         2
0  0.460247  0.364797  0.506024
1  0.214764  0.869629  0.802114
2  0.306094  0.318350  0.609047
3  0.352921  0.403321  0.364716


In [6]:
print(p.major_xs(1))

      Item1     Item2
0  0.214764  0.993961
1  0.869629  0.061791
2  0.802114       NaN


In [8]:
print(p.minor_xs(1))

      Item1     Item2
0  0.364797  0.704512
1  0.869629  0.061791
2  0.318350  0.592270
3  0.403321  0.521774
